services:
  evolve_agent:
    build:
      context: ./evolve_agent
      dockerfile: Dockerfile.dev
    volumes:
      - ./evolve_agent:/workspace/evolve_agent
      - ./pytest.ini:/workspace/pytest.ini
      - ./pyproject.toml:/workspace/pyproject.toml
      - ./logs:/workspace/logs
    environment:
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1  # Prevents Python from buffering stdout and stderr
