services:
  evolve_agent:
    build:
      context: ./evolve_agent
      dockerfile: Dockerfile
    working_dir: /workspace/evolve_agent
    restart: always
    volumes:
      - ./logs:/workspace/logs
    environment:
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    ports:
      - "8888:8000"


  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./volumes/n8n_data:/home/node/.n8n
