services:
  evolve_agent:
    build:
      context: ./evolve_agent
      dockerfile: Dockerfile
    working_dir: /evolve_agent
    restart: always
    ports:
      - "8888:8000"
    environment:
      SUB_DOMAIN: evolve_agent
    networks:
      - default

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./volumes/n8n_data:/home/node/.n8n
    networks:
      - default
