services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://evolve_agent:8000/api/v1
      - WS_URL=ws://evolve_agent:8000/api/v1
      - N8N_PUBLIC_URL=${N8N_PUBLIC_URL}
    restart: always
    depends_on:
      - evolve_agent

  evolve_agent:
    build:
      context: ./evolve_agent
      dockerfile: Dockerfile
    working_dir: /workspace/evolve_agent
    restart: always
    volumes:
      - ./logs:/workspace/logs
    environment:
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    ports:
      - "8888:8000"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./volumes/n8n_data:/home/node/.n8n
